version: '3.3'

services:
  web:
    image: nginx
    volumes:
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - "80:80"
    restart: always
    links:
      - php
    depends_on:
      - php
      - db
  php:
    build: docker
    restart: always
    volumes:
      - ./docker/conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./app/:/var/www/html
    depends_on:
      - composer
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
  composer:
    image: composer:latest
    volumes:
      - ./app:/app
    command: install
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/conf/postgresql/:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db-data: ~
